name: Build Electron App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Build and Release Electron App
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]
        # os: [macos-latest, windows-latest, ubuntu-latest]  # Uncomment to enable all platforms
        
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install System Dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev python3-tk python3-pil.imagetk
          
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Download VC++ Redistributable (Windows only)
        if: matrix.os == 'windows-latest'
        run: |
          if (!(Test-Path -Path build-resources)) { New-Item -ItemType Directory -Path build-resources }
          curl -L -o build-resources/vc_redist.x64.exe https://aka.ms/vs/17/release/vc_redist.x64.exe
        shell: pwsh
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Bundle Python with PyInstaller
        run: node scripts/bundle-python.js
        
      - name: Build Webpack
        run: npm run build
        
      - name: Build Electron App
        run: npm run package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
          WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifacts
          path: |
            dist/*.dmg
            dist/*.exe
            dist/*.deb
            dist/*.AppImage
            dist/*.zip
          if-no-files-found: ignore
          
  create-release:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Display structure of downloaded files
        run: ls -R artifacts
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/**/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}